### ISSUE TITLE
Manifest path in test:program-rust script does not exist

### ISSUE THREAD

**Issue by ccddan** [Ackee-Blockchain/summer-school-of-solana-2022#10]
The manifest path points to `./program-rust/Cargo.toml` which does not exist in the repo, it should be `./program/Cargo.toml` instead.

**Comment by tribuste** [comment]
Fixed here -> https://github.com/Ackee-Blockchain/summer-school-of-solana-2022/commit/7cfca6d5e0cf70bed39b70e82346cabeddc61c22
