### ISSUE TITLE
Found argument 'build-bpf' which wasn't expected

### ISSUE THREAD

**Issue by ccddan** [Ackee-Blockchain/summer-school-of-solana-2022#9]
After cloning the repo and installing dependencies, build script fails with the following message:

```log
npm run build:program-rust

> counter@0.0.1 build:program-rust
> cargo build-bpf --manifest-path=./program/Cargo.toml --bpf-out-dir=dist/program

Warning: cargo-build-bpf is deprecated. Please, use cargo-build-sbf
cargo-build-bpf child: /home/ccarlos/.local/share/solana/install/active_release/bin/cargo-build-sbf build-bpf --manifest-path=./program/Cargo.toml --sbf-out-dir=dist/program
error: Found argument 'build-bpf' which wasn't expected, or isn't valid in this context

USAGE:
    cargo-build-sbf [OPTIONS] [-- <cargo_args>...]

For more information try --help
```

I was not sure if the `postinstall` had something to do with the issue (it is upgrading cargo dependencies automatically which might break things), so, I cloned the repo again, disabled the `postinstall` script in package.json file, installed dependencies and tried the build script again. Same result, issue still persists.

**System Info**
* OS: Ubuntu 20.04.4 LTS
* cargo: 1.61.0
* node: 16.15.1
* npm: 8.11.0
* solana-cli: 1.11.0
* anchor-cli: 0.24.2

**Comment by ccddan** [comment]
For the sake of curiosity, I replaced `cargo build-bpf` by `cargo-build-sbf` and... of course it did not work:

```log
   Compiling bv v0.11.1
   Compiling num-traits v0.2.15
   Compiling crossbeam-channel v0.5.5
   Compiling num_cpus v1.13.1
error: target is not supported, for more information see: https://docs.rs/getrandom/#unsupported-targets
   --> src/lib.rs:267:9
    |
267 | /         compile_error!("\
268 | |             target is not supported, for more information see: \
269 | |             https://docs.rs/getrandom/#unsupported-targets\
270 | |         ");
    | |__________^

error[E0433]: failed to resolve: use of undeclared crate or module `imp`
   --> src/lib.rs:291:5
    |
291 |     imp::getrandom_inner(dest)
    |     ^^^ use of undeclared crate or module `imp`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `getrandom` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by vmarcin** [comment]
try to run `cargo build-bpf --help` and let me know what is the output of this command for you

**Comment by ccddan** [comment]
> try to run `cargo build-bpf --help` and let me know what is the output of this command for you

Here's the output:
```log
❯ cargo build-bpf --help
Warning: cargo-build-bpf is deprecated. Please, use cargo-build-sbf
cargo-build-bpf child: /home/ccarlos/.local/share/solana/install/active_release/bin/cargo-build-sbf build-bpf --help
error: Found argument 'build-bpf' which wasn't expected, or isn't valid in this context

USAGE:
    cargo-build-sbf [OPTIONS] [-- <cargo_args>...]

For more information try --help
```

**Comment by vmarcin** [comment]
You are using the edge version of solana-cli, and that's the problem. Run this command please to install the older version, and you should be fine:

`sh -c "$(curl -sSfL https://release.solana.com/v1.10.26/install)"`

Let me know if it helped :)

**Comment by ccddan** [comment]
> You are using the edge version of solana-cli, and that's the problem. Run this command please to install the older version, and you should be fine:
> 
> `sh -c "$(curl -sSfL https://release.solana.com/v1.10.26/install)"`
> 
> Let me know if it helped :)

Yes, it helped. I can build the project now. At some point, during installation, I was requested to update to the latest version, and since I could not see any specific version in lesson 01 setup instructions, I upgraded it.

I can confirm that version 1.10.24 solve the issue. Thanks for the support!!
